chore(deps): Upgrade react-native-vision-camera to v4 (& supporting libraries)
mrousavy/VisionCameraSkiaDemo pull request #2
Opened 2024-04-24 03:31 UTC by ttuck303

Found this amazing tutorial, and figured I would update the code now that we have Skia processors back in Vision Camera 4.

Updates libraries:
"@shopify/react-native-skia": "^0.1.202" -> "^1.2.3"
"react-native-fast-tflite": "^0.2.0" -> "^1.2.0"
"react-native-vision-camera": "^3.0.0-rc.7" -> "^4.0.1"
"react-native-worklets-core": "^0.2.0" -> "^2.1.1"

Adds:
"react-native-reanimated": "^3.8.1"

Tested on iPhone 12 Pro:
https://github.com/mrousavy/VisionCameraSkiaDemo/assets/1236380/55420512-bebb-4d5a-8477-f52bd9c7b32d

Two possible concerns:
1. the pose scaling seems overly large / not connected to the head
2. (possibly related to 1) hard coded the camera width to 1080, since original format code was not working for me at the time

Thanks for all you do for the RN Community!

2024-04-29 10:27 UTC, mrousavy commented
amazing thank you!

2024-04-29 10:29 UTC, mrousavy requested changes
amazing thank you - just two minor changes

2024-04-29 10:29 UTC, mrousavy commented on src/App.tsx
> +  const device = devices.find(d => d.position === 'front');
Please simply use `useCameraDevice('front')` here - it's more efficient.

2024-04-29 10:29 UTC, mrousavy commented on package.json
> +    "vision-camera-resize-plugin": "^2.1.1"
Please upgrade to latest 3.x.x, this fixes Android

2024-05-07 04:25 UTC, ttuck303 commented
- updated libraries and hooks as requested
- I believe the scaling issue in the Y-axis is due to cropping the rectangular image to a square for the pose estimation model, then scaling the coordinates from the model to the rectangular shape without accounting for the cropped area. But not a big deal for this demo app

2024-05-08 11:13 UTC, mrousavy commented
Thanks! Yea you just need to pass `pixelFormat="yuv"` to the Camera.

2024-05-08 11:14 UTC, mrousavy commented on src/App.tsx
> -  const SCALE = (format?.videoWidth ?? VIEW_WIDTH) / VIEW_WIDTH;
Please don't hardcode this. This is not a good idea.

Above you removed the code that selected a Format, let's keep using a Format so we know video size in advance.

2024-05-24 21:00 UTC, ttuck303 commented
Updated with requested changes:
- added back dynamic scale
- added pixel format based on device platform
- updated android minsdk and compile sdk to required versions
- added rotation hack to properly orient Android


Something is still incorrect with Android:
- if I leave orientation at 0 in resize plugin, the final image is rotated 90
- if I rotate the orientation 270 in the resize plugin, the final image is properly oriented, but squished. 
Hoping its an obvious fix. 

Running on iOS:
https://github.com/mrousavy/VisionCameraSkiaDemo/assets/1236380/084d517e-5606-4c6e-8498-8c8eef07440c

Running on Android with 270deg rotation:
https://github.com/mrousavy/VisionCameraSkiaDemo/assets/1236380/92117f84-a0a9-4bd4-aa16-a90232c28a57

Running on Android with 0deg rotation:
https://github.com/mrousavy/VisionCameraSkiaDemo/assets/1236380/268c0fbc-28b6-48af-9b78-02dfc248036c

2024-05-27 08:59 UTC, merged

2024-05-27 08:59 UTC, mrousavy commented
Awesome work man! Thank you